---
title: Introduction
---


Why is insurance pricing more difficult than for usual G&S?

* Promise to pay if a certain event takes place in future
* Ultimate cost is unknown at time of sale


Ratemaking
: Process of setting prices in P&C






Rating Manuals
==============================


premium
: Price paid by the insurance consumer

Premium = Rate x Exposure

rating manual
: document with info to classify risks and calc premium for that risk

__output of ratemaking = info to create or modify a rating manual__







Basic Insurance Terms
============================


Exposure
--------------

Exposure
: Basic unit of risk underlying insurance premium. 

Varies considerably by LoB.


Written Exposure
: Total exposure from policies issued (written) *during a period of time* (CY 
or quarter)


Earned Expo
: Portion of written expo for which coverage has been provided 
_as of a certain point in time._


Unearned Expo
: Portion of WE for which coverage has NOT been provided as of a certain
point in time.


In-force Expo
: Number of insured units exposed to a loss *at a given point in time*.





Premium
-----------------

Premium
: amount the insure pays for insurance coverage. 
: aggregate premium amount for *a group of insured* over *a period of time*.


WP
: Total premium from policies issued *during a specified period*.


EP
: Portion of the written premium for which coverage has been provided as of
a certain period of time.


unEP
: Portion of WP for which coverage has NOT been provided *as of certain period of time*


in-FP
: *full term* premium for policies in effect at a given point in time.




Claim
------------

insurance policy
: exchange of premium for against a promise to indemnify the insured for financial
consequences of an event covered.


claim
: Demand of indemnification under an insurance policy


claimant
: person making an insurance claim


date of loss/accident date/occurrence date
: date of the event that caused a loss


*if loss is result of a continuous or repeated exposure to substantially the*
*same general hazard condition, the date of loss is the date the loss became*
*apparent*


report date
: date at which the claimant reports the claim to the insurer.


unreported claims/ IBNR claims
: Existing claims, not currently known by the insurer




Loss
---------------------

Loss
: amount of compensation/indemnity paid under insurance policy.


paid loss
: amount that have been paid to a claimant


case reserve
: *Estimate* of amount needed to *ultimately* settle a given claim. Excludes
any payment already made.


reported loss
: Paid Loss + Case Reserve


ultimate loss
: amount needed to close and settle *all claims* for a *specified group* of
policies.


IBNR reserve
: amount estimated to ultimately settle unreported claims.


IBNER reserve/development on known claims
: amount estimated to ultimately settle *reported* claims, minus case reserves.



Difference between ultimate losses and reported losses:
* unreported claims
* change on reported losses over time

**Estimated Ult Losses = Reported Losses + IBNR Reserve + IBNER Reserve**





Loss Adjustment Expenses
--------------------------------

LAE
: expenses incurred in process of settling claims, *in addition* to the indemnity.


ALAE
: claim-related expenses directly attributable to specific claim. (e.g. fees for
outside legal counsel).


ULAE
: claim related expenses that cannot be attributed to a specific claim (e.g.
salaries of claims dpt)


*LAE = ALAE + ULAE*





Underwriting Expenses
--------------------------------


UW expense / operational and admin expenses
: expenses in *acquisition* and *servicing* of policies, *in addition to LAE*.


4 categories of UW xp:
* Commission and brokerage
    + paid to broker or insurance agent, as compensation for generating biz
    + as % of written premium
* Other Acquisition
    + other xp for acquiring biz
    + e.g. ads, mailings
* General
    + other xp for operation and misc
    + e.g. home office
* Taxes, Licenses and fees
    + excludes fed income taxes
    



UW Profit
------------------


UW profit/operating income
: sum of profit generated by ind policies = income - outgo


Investment income
: income generated by investing funds held by insurance company


*Profit = UW profit + Investment profit*








Fundamental Insurance Equations
========================================


**Fundamental insurance equation:**

**Premium = Losses + LAE + UW Exp + UW profit**


*Goal of ratemaking: balance fundamental eq*

- Cover all costs
- achieve target UW profit

> A rate provides for all costs associated with transfer of risk.
>> CAS Ratemaking Principles


key points in achieving balance
* Ratemaking is prospective
* Balance should be attained at *aggregate and ind levels*.







Ratemaking is Prospective
---------------------------

> A rate is an estimate of the exp value of future costs

- Historic costs should be used to the extent they provide info on future
expected costs -> restatement


Reasons that necessitate a restatement of hist xp:
* Rate change
* Op changes
* Inflation
* Change in mix of biz
* Law changes


1. Use hist as starting point
2. Make adj for each of item above as needed, given expected level during future
rate period.


*Reasonable expectation* that premium will cover EL and XP and achieve target profit.





Overall and Individual Balance
-------------------------------


equilibrium at agg level => cover costs and provide profit


> A rate provides for the costs associated with an **individual** risk transfer.
>> CAS Ratemaking principles


should adjust premium for riskiness of policies.







Basic Insurance Ratios
=====================



Frequency
-----------------

Freq = # Claims / # Expo


* spot industry trends
* measure effectiveness of UW actions




Severity
---------------------

Sev = Losses / # claims


* spot loss trends
* impact of changes in claims handling




Pure premium/Loss Cost
-----------------------------

Pure premium = Losses / # Expo
             = Freq x Severity
             
             
* typically reported/ult losses and earned expo
* overall trends due to both freq and sev changes




Avg Premium
---------------------

Avg premium = Premium / # Expos


* premium and expo should be on same basis
* changes in mix of biz (if adj for rate changes)



Loss Ratio
------------------------------

LR = Losses / Premium
   = Pure premium / avg premium

* Portion of premium used to pay losses
* primary measure of rate adequacy (w/ LAE)



LAE ratio
-----------------------------

LAE ratio = LAE / *Losses*


* monitor stability of LAE
* benchmark with competition



UW xp ratio
---------------------

UW xp ratio = UW xp / Premium


* portion of premium for UW xp
* need to match expenses types with premium
  + incurred at onset: C&B, OA, TLF => WP
  + incurred during policy: GE => EP
* spot trends with inflation
* bm against comp




Operating Expense ratio
---------------------------

OER = UW xp ratio + LAE / Premium


* portion of premium for operation
* key det. of profitability





Combined Ratio
---------------------------

CR = LR + LAE / EP + UW xp / WP
   = LR + OER
   
* Beware of double counting
* primary measure of profitability




Retention Ratio
----------------------------

Ret ratio = # of renewed polices / # policies up for renewal


* Monitor comp of rates
* key param to project future premium




Close ratio/hit ratio/quote-to-close ratio/conversion rate
----------------------------------------------------------------

Close Ratio = # accepted quotes / # quotes

































